<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
          $products = [
    [
        'name' => 'Default Product',
        'barcode' => 'PRD' . str_pad(1, 8, '0', STR_PAD_LEFT),
        'brand_id' => 1,
        'category_id' => 1,
        'type_id' => 1,
        'discount_id' => 1,
        'tax_id' => 1,
        'shop_quantity' => 1,
        'shop_low_stock_margin' => 0,
        'store_quantity' => 0,
        'store_low_stock_margin' => 0,
        'purchase_price' => 0.00,
        'wholesale_price' => 0.00,
        'retail_price' => 0.00,
        'return_product' => true,
        'purchase_unit_id' => 1,
        'sales_unit_id' => 1,
        'transfer_unit_id' => 1,
        'purchase_to_transfer_rate' => 0.00,
        'transfer_to_sales_rate' => 0.00,
        'status' => 2,
        'image' => null,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Smartphone',
        'barcode' => 'PRD' . str_pad(2, 8, '0', STR_PAD_LEFT),
        'brand_id' => 2,
        'category_id' => 2,
        'type_id' => 1,
        'discount_id' => 2,
        'tax_id' => 1,
        'shop_quantity' => 50,
        'shop_low_stock_margin' => 5,
        'store_quantity' => 100,
        'store_low_stock_margin' => 10,
        'purchase_price' => 300.00,
        'wholesale_price' => 350.00,
        'retail_price' => 400.00,
        'return_product' => true,
        'purchase_unit_id' => 1,
        'sales_unit_id' => 1,
        'transfer_unit_id' => 1,
        'purchase_to_transfer_rate' => 1.00,
        'transfer_to_sales_rate' => 1.00,
        'status' => 1,
        'image' => null,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Laptop',
        'barcode' => 'PRD' . str_pad(3, 8, '0', STR_PAD_LEFT),
        'brand_id' => 2,
        'category_id' => 2,
        'type_id' => 1,
        'discount_id' => 3,
        'tax_id' => 1,
        'shop_quantity' => 20,
        'shop_low_stock_margin' => 3,
        'store_quantity' => 50,
        'store_low_stock_margin' => 5,
        'purchase_price' => 700.00,
        'wholesale_price' => 800.00,
        'retail_price' => 900.00,
        'return_product' => true,
        'purchase_unit_id' => 1,
        'sales_unit_id' => 1,
        'transfer_unit_id' => 1,
        'purchase_to_transfer_rate' => 1.00,
        'transfer_to_sales_rate' => 1.00,
        'status' => 1,
        'image' => null,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'T-Shirt',
        'barcode' => 'PRD' . str_pad(4, 8, '0', STR_PAD_LEFT),
        'brand_id' => 3,
        'category_id' => 3,
        'type_id' => 1,
        'discount_id' => 1,
        'tax_id' => 1,
        'shop_quantity' => 100,
        'shop_low_stock_margin' => 10,
        'store_quantity' => 200,
        'store_low_stock_margin' => 20,
        'purchase_price' => 5.00,
        'wholesale_price' => 8.00,
        'retail_price' => 12.00,
        'return_product' => true,
        'purchase_unit_id' => 8,
        'sales_unit_id' => 8,
        'transfer_unit_id' => 8,
        'purchase_to_transfer_rate' => 1.00,
        'transfer_to_sales_rate' => 1.00,
        'status' => 1,
        'image' => null,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Cooking Oil (1L)',
        'barcode' => 'PRD' . str_pad(5, 8, '0', STR_PAD_LEFT),
        'brand_id' => 4,
        'category_id' => 4,
        'type_id' => 1,
        'discount_id' => 4,
        'tax_id' => 1,
        'shop_quantity' => 80,
        'shop_low_stock_margin' => 10,
        'store_quantity' => 150,
        'store_low_stock_margin' => 20,
        'purchase_price' => 6.00,
        'wholesale_price' => 7.50,
        'retail_price' => 9.00,
        'return_product' => true,
        'purchase_unit_id' => 4,
        'sales_unit_id' => 4,
        'transfer_unit_id' => 4,
        'purchase_to_transfer_rate' => 1.00,
        'transfer_to_sales_rate' => 1.00,
        'status' => 1,
        'image' => null,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Rice (10kg)',
        'barcode' => 'PRD' . str_pad(6, 8, '0', STR_PAD_LEFT),
        'brand_id' => 5,
        'category_id' => 10,
        'type_id' => 1,
        'discount_id' => 7,
        'tax_id' => 1,
        'shop_quantity' => 40,
        'shop_low_stock_margin' => 5,
        'store_quantity' => 100,
        'store_low_stock_margin' => 10,
        'purchase_price' => 18.00,
        'wholesale_price' => 22.00,
        'retail_price' => 26.00,
        'return_product' => true,
        'purchase_unit_id' => 2,
        'sales_unit_id' => 2,
        'transfer_unit_id' => 2,
        'purchase_to_transfer_rate' => 1.00,
        'transfer_to_sales_rate' => 1.00,
        'status' => 1,
        'image' => null,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Football',
        'barcode' => 'PRD' . str_pad(7, 8, '0', STR_PAD_LEFT),
        'brand_id' => 6,
        'category_id' => 6,
        'type_id' => 1,
        'discount_id' => 1,
        'tax_id' => 1,
        'shop_quantity' => 30,
        'shop_low_stock_margin' => 5,
        'store_quantity' => 60,
        'store_low_stock_margin' => 10,
        'purchase_price' => 10.00,
        'wholesale_price' => 14.00,
        'retail_price' => 18.00,
        'return_product' => true,
        'purchase_unit_id' => 8,
        'sales_unit_id' => 8,
        'transfer_unit_id' => 8,
        'purchase_to_transfer_rate' => 1.00,
        'transfer_to_sales_rate' => 1.00,
        'status' => 1,
        'image' => null,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Toy Car',
        'barcode' => 'PRD' . str_pad(8, 8, '0', STR_PAD_LEFT),
        'brand_id' => 7,
        'category_id' => 8,
        'type_id' => 1,
        'discount_id' => 8,
        'tax_id' => 1,
        'shop_quantity' => 60,
        'shop_low_stock_margin' => 8,
        'store_quantity' => 120,
        'store_low_stock_margin' => 15,
        'purchase_price' => 3.00,
        'wholesale_price' => 5.00,
        'retail_price' => 7.00,
        'return_product' => true,
        'purchase_unit_id' => 8,
        'sales_unit_id' => 8,
        'transfer_unit_id' => 8,
        'purchase_to_transfer_rate' => 1.00,
        'transfer_to_sales_rate' => 1.00,
        'status' => 1,
        'image' => null,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Car Engine Oil',
        'barcode' => 'PRD' . str_pad(9, 8, '0', STR_PAD_LEFT),
        'brand_id' => 8,
        'category_id' => 9,
        'type_id' => 1,
        'discount_id' => 9,
        'tax_id' => 1,
        'shop_quantity' => 25,
        'shop_low_stock_margin' => 5,
        'store_quantity' => 50,
        'store_low_stock_margin' => 10,
        'purchase_price' => 12.00,
        'wholesale_price' => 16.00,
        'retail_price' => 20.00,
        'return_product' => true,
        'purchase_unit_id' => 4,
        'sales_unit_id' => 4,
        'transfer_unit_id' => 4,
        'purchase_to_transfer_rate' => 1.00,
        'transfer_to_sales_rate' => 1.00,
        'status' => 1,
        'image' => null,
        'created_at' => now(),
        'updated_at' => now(),
    ],
    [
        'name' => 'Notebook',
        'barcode' => 'PRD' . str_pad(10, 8, '0', STR_PAD_LEFT),
        'brand_id' => 9,
        'category_id' => 5,
        'type_id' => 1,
        'discount_id' => 1,
        'tax_id' => 1,
        'shop_quantity' => 200,
        'shop_low_stock_margin' => 20,
        'store_quantity' => 500,
        'store_low_stock_margin' => 50,
        'purchase_price' => 0.50,
        'wholesale_price' => 0.80,
        'retail_price' => 1.20,
        'return_product' => true,
        'purchase_unit_id' => 8,
        'sales_unit_id' => 8,
        'transfer_unit_id' => 8,
        'purchase_to_transfer_rate' => 1.00,
        'transfer_to_sales_rate' => 1.00,
        'status' => 1,
        'image' => null,
        'created_at' => now(),
        'updated_at' => now(),
    ],
 

    ];


        foreach ($products as $product) {
            Product::updateOrCreate(
                ['barcode' => $product['barcode']],
                $product
            );
        }
    }
}
